# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2019-08-16 17:53
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tv_shows_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shows',
            name='release_date',
            field=models.DateField(default=datetime.date(2019, 8, 16)),
        ),
    ]
